package org.sistcoop.cooperativa.models.jpa.entities;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * TransaccionBovedaCaja generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_ENTIDAD", indexes = { @Index(columnList = "id") })
@XmlRootElement
@XmlAccessorType(XmlAccessType.PROPERTY)
public class TransaccionBovedaEntidadEntity extends TransaccionInternaEntity
		implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private EntidadEntity entidad;
	private HistorialBovedaEntity historialBoveda;

	private Set<DetalleTransaccionBovedaEntidadEntity> detalle = new HashSet<DetalleTransaccionBovedaEntidadEntity>();

	public TransaccionBovedaEntidadEntity() {
		// TODO Auto-generated constructor stub
	}

	@Id
	@GeneratedValue(generator = "SgGenericGenerator")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotNull
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(foreignKey = @ForeignKey)
	public EntidadEntity getEntidad() {
		return entidad;
	}

	public void setEntidad(EntidadEntity entidad) {
		this.entidad = entidad;
	}

	@NotNull
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(foreignKey = @ForeignKey)
	public HistorialBovedaEntity getHistorialBoveda() {
		return historialBoveda;
	}

	public void setHistorialBoveda(HistorialBovedaEntity historialBoveda) {
		this.historialBoveda = historialBoveda;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaccionBovedaEntidad")
	public Set<DetalleTransaccionBovedaEntidadEntity> getDetalle() {
		return detalle;
	}

	public void setDetalle(Set<DetalleTransaccionBovedaEntidadEntity> detalle) {
		this.detalle = detalle;
	}

}
